name: Secret Scan

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          set -e
          GL_VERSION=8.18.4
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v${GL_VERSION}/gitleaks_${GL_VERSION}_linux_x64.tar.gz | tar -xz

      - name: Run Gitleaks
        id: run_gitleaks
        run: |
          set +e
          ./gitleaks detect --source . --redact --report-format sarif --report-path gitleaks.sarif
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Ensure SARIF exists
        if: always()
        run: |
          if [ ! -f gitleaks.sarif ]; then
            echo '{"version":"2.1.0","runs":[]}' > gitleaks.sarif
          fi

      - name: Upload SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
